export const UPDATE_CHARACTER_PENDING = 'UPDATE_CHARACTER_PENDING'
export const UPDATE_CHARACTER_REJECTED = 'UPDATE_CHARACTER_REJECTED'
export const UPDATE_CHARACTER_FULFILLED = 'UPDATE_CHARACTER_FULFILLED'

export const DELETE_CHARACTER_PENDING = 'DELETE_CHARACTER_PENDING'
export const DELETE_CHARACTER_REJECTED = 'DELETE_CHARACTER_REJECTED'
export const DELETE_CHARACTER_FULFILLED = 'DELETE_CHARACTER_FULFILLED'

export const FETCH_CHARACTER_PENDING = 'FETCH_CHARACTER_PENDING'
export const FETCH_CHARACTER_REJECTED= 'FETCH_CHARACTER_REJECTED'
export const FETCH_CHARACTER_FULFILLED = 'FETCH_CHARACTER_FULFILLED'

export const FETCH_CHARACTERS_PENDING = 'FETCH_CHARACTERS_PENDING'
export const FETCH_CHARACTERS_REJECTED= 'FETCH_CHARACTERS_REJECTED'
export const FETCH_CHARACTERS_FULFILLED = 'FETCH_CHARACTERS_FULFILLED'

export const MODIFY_STAT_PENDING = 'MODIFY_STAT_PENDING'
export const MODIFY_STAT_FULFILLED = 'MODIFY_STAT_FULFILLED'
export const MODIFY_STAT_REJECTED = 'MODIFY_STAT_REJECTED'

export const ADD_CHARACTER_PENDING = 'ADD_CHARACTER_PENDING'
export const ADD_CHARACTER_FULFILLED = 'ADD_CHARACTER_FULFILLED'
export const ADD_CHARACTER_REJECTED = 'ADD_CHARACTER_REJECTED'

export const CHARACTER_ADD_MOVE_PENDING = 'CHARACTER_ADD_MOVE_PENDING'
export const CHARACTER_ADD_MOVE_FULFILLED = 'CHARACTER_ADD_MOVE_FULFILLED'
export const CHARACTER_ADD_MOVE_REJECTED = 'CHARACTER_ADD_MOVE_REJECTED'